server:
  port: 8080

langchain4j:
  open-ai:
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: apiKey
      model-name: qwen-plus
      log-requests: true
      log-responses: true
